#####
# cli : ansible-playbook junos_config_push.yml -i hosts
#####

- name: Push Configuration to Junos equipment
  hosts: ALL
  gather_facts: no
  pre_tasks:
    - include_vars: vars.yml

  tasks: 
    - name: Checking LAB devices connectivity
      connection: local
      wait_for: 
        host: '{{ ansible_host }}'
        port: 22  
        timeout: 5

    - name: Push configuration on each devices  from the {{ configs_dir }} directory
      connection: local
      junos_config:
        host: '{{ ansible_host }}'
        port: 22 
        username: '{{ ansible_ssh_user }}'
        password: '{{ ansible_ssh_pass }}'
        src: '{{ configs_dir }}{{ hostname }}.txt'
        check_commit: yes
        confirm_commit: yes
        update: override